export type Tier = 'free' | 'register' | 'cell' | 'supplier';

export interface RouteRow {
  method: string;
  path: string;
  tier: Tier;
  summary: string;
}

// Cross-checked directly against src/assurance/api/*_routes.py and
// src/assurance/api/deps.py (Annotated[Principal, Anyone|Registered|Machine|
// Attesting|Supplying]) at the time this page was written. Re-verify against
// /openapi.json (generated by scripts/export_openapi.py from the same code)
// before trusting this table blindly after a routes change — it is not
// auto-generated, deliberately: a curated, tier-grouped view reads better
// than all 44 raw paths, but that means a human has to keep it honest.
// Shared by /developers, /cli, and /connectors/mcp so the three don't drift.
export const ROUTES: RouteRow[] = [
  { method: 'GET', path: '/v1/spec/fields', tier: 'free', summary: 'The platform field specification for a track/stage' },
  { method: 'POST', path: '/v1/spec/validate', tier: 'free', summary: 'Validate a draft submission without recording it' },
  { method: 'GET', path: '/v1/plans', tier: 'free', summary: 'What is on sale — this table, live' },
  { method: 'POST', path: '/v1/machine/separation', tier: 'free', summary: 'ISO/TS 15066 protective separation distance' },
  { method: 'POST', path: '/v1/machine/bundle/check', tier: 'free', summary: "Re-verify someone else's evidence bundle" },
  { method: 'POST', path: '/v1/machinery/diff', tier: 'free', summary: 'Is the machine still the configuration you signed off?' },
  { method: 'POST', path: '/v1/machinery/passport/check', tier: 'free', summary: "Re-verify someone else's machine passport" },
  { method: 'POST', path: '/v1/fleet/advisory/check', tier: 'free', summary: 'Is this one machine affected by this advisory?' },
  { method: 'POST', path: '/v1/fleet/declaration/check', tier: 'free', summary: 'Does this declaration still describe the machine?' },
  { method: 'GET', path: '/v1/ledger/attest/key', tier: 'free', summary: 'The public key this service counter-signs with' },
  { method: 'POST', path: '/v1/ledger/attest/verify', tier: 'free', summary: 'Check an attestation log' },
  { method: 'GET', path: '/v1/supplier/feed/{id}', tier: 'free', summary: 'Read a hosted supplier advisory feed' },

  { method: 'GET', path: '/v1/register', tier: 'register', summary: 'The Article 14 register for your account' },
  { method: 'GET', path: '/v1/register/breaches', tier: 'register', summary: 'Cases past a deadline clock' },
  { method: 'GET', path: '/v1/cases', tier: 'register', summary: 'List cases' },
  { method: 'POST', path: '/v1/cases/{id}/triage', tier: 'register', summary: 'Record a triage decision' },
  { method: 'POST', path: '/v1/cases/{id}/filings', tier: 'register', summary: 'Record a platform filing' },
  { method: 'GET', path: '/v1/ledger/verify', tier: 'register', summary: 'Verify the hash chain' },

  { method: 'POST', path: '/v1/machine/verify', tier: 'cell', summary: 'Verify a recorded machine run against its declared envelope' },
  { method: 'POST', path: '/v1/machinery/manifest', tier: 'cell', summary: 'Seal a safety software manifest' },
  { method: 'POST', path: '/v1/machinery/coverage', tier: 'cell', summary: 'Which safety functions still have valid evidence' },
  { method: 'POST', path: '/v1/machinery/passport', tier: 'cell', summary: "Seal the machine's evidence position" },
  { method: 'GET', path: '/v1/fleet/machines', tier: 'cell', summary: 'Every enrolled machine, worst coverage first' },
  { method: 'POST', path: '/v1/fleet/advisory', tier: 'cell', summary: 'Fan an advisory out across the whole fleet' },
  { method: 'POST', path: '/v1/fleet/declare', tier: 'cell', summary: 'Bind a Declaration of Conformity to a configuration' },
  { method: 'POST', path: '/v1/ledger/attest', tier: 'cell', summary: 'Counter-sign the head of your ledger' },
  { method: 'GET', path: '/v1/ledger/attest/log', tier: 'cell', summary: 'Every attestation for your account' },

  { method: 'POST', path: '/v1/supplier/advisory', tier: 'supplier', summary: 'Publish a signed advisory to your hosted feed' },
];

export const TIER_LABEL: Record<Tier, string> = {
  free: 'Validator — free',
  register: 'Register — €390/mo',
  cell: 'Cell — €1,290/mo',
  supplier: 'Supplier — contact sales',
};

// The CLI's domain/verb tree (python -m assurance <domain> <verb>), checked
// against each domain's --help at the time this was written — re-verify the
// same way before trusting it after a CLI change. Not every CLI verb calls
// the hosted API: kit and watch are offline-first by design and have no API
// equivalent; art14/bridge manage local case state before anything is filed.
export interface CliDomain {
  domain: string;
  verbs: string[];
  summary: string;
  apiTier?: Tier;
}

export const CLI_DOMAINS: CliDomain[] = [
  { domain: 'kit', verbs: ['init', 'run', 'check'], summary: 'Enrol a plant’s machines without anything leaving it — offline by design, no API equivalent.' },
  { domain: 'machine', verbs: ['separation', 'verify', 'check'], summary: 'ISO/TS 15066 separation and recorded-run verification.', apiTier: 'free' },
  { domain: 'machinery', verbs: ['record-manifest', 'record-change', 'diff', 'coverage', 'passport', 'check'], summary: 'Annex III safety software manifests and the staleness join.', apiTier: 'cell' },
  { domain: 'fleet', verbs: ['list', 'advisory', 'declare', 'declaration'], summary: 'Advisory fan-out and Declaration binding across a fleet.', apiTier: 'cell' },
  { domain: 'attest', verbs: ['keygen', 'sign', 'verify', 'log'], summary: 'Counter-signed head attestation — catches deletion, not just editing.', apiTier: 'cell' },
  { domain: 'watch', verbs: ['run', 'status'], summary: 'The component that runs when nobody is looking — local only, no API equivalent.' },
  { domain: 'supplier', verbs: ['keygen', 'publish', 'withdraw', 'verify', 'list'], summary: 'Sign and publish advisories to a hosted feed.', apiTier: 'supplier' },
  { domain: 'art14', verbs: ['signal', 'awareness', 'triage', 'availability', 'measure', 'file', 'notify-users', 'validate', 'fields', 'case', 'register', 'verify', 'export'], summary: 'Case triage and the two Article 14 deadline clocks.', apiTier: 'register' },
  { domain: 'bridge', verbs: ['art14'], summary: 'Assembles the Article 14 export from local case state — local only.' },
  { domain: 'collect', verbs: ['check-plan', 'probe', 'run'], summary: 'Finds the vendor tool’s own volatile headers before they produce a year of false drift alarms.' },
];
