"""Machine execution traces, and what a trace is allowed to prove.

A trace is what the machine actually did: a time series of pose, speed,
operating mode, measured separation from a detected person, and — where the
cell claims power and force limiting — contact force.

The reason this module exists rather than a CSV reader is provenance. A trace
recorded in a simulator and a trace recorded from the cell on the shop floor
are the same shape and are worth entirely different things. Conflating them is
how a validation report comes to assert physical behaviour on the strength of
a model. :class:`Provenance` carries the distinction into the type system, and
:attr:`Provenance.tier_ceiling` stops a bundle claiming more than its input
can support.
"""

from __future__ import annotations

import csv
import json
from collections.abc import Iterable, Iterator, Sequence
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

from assurance.core.errors import AssuranceError
from assurance.core.identity import content_hash_of, format_utc, parse_utc
from assurance.core.tiers import AssuranceTier

__all__ = [
    "OperatingMode",
    "Provenance",
    "Sample",
    "Trace",
    "TraceError",
]


class TraceError(AssuranceError):
    """A trace is malformed, or is being asked to support a claim it cannot."""


class Provenance(StrEnum):
    """Where the samples came from. This is the ceiling on every claim made from them."""

    #: Generated by a simulator or a digital twin. Tells you about the model.
    SIMULATION = "simulation"
    #: Recorded from the real machine off-line: a bench, a commissioning run,
    #: a witnessed test. Real hardware, controlled conditions.
    BENCH = "bench"
    #: Recorded from the machine in production, doing the work it is sold to do.
    FIELD = "field"

    @property
    def tier_ceiling(self) -> AssuranceTier:
        """The highest tier a verification over this trace may reach.

        Simulation can never reach VALIDATED: no simulator has ever measured a
        protective stop. CERTIFIED is never reachable from a trace at all — it
        requires an accredited third party, not a file.
        """
        if self is Provenance.SIMULATION:
            return AssuranceTier.COMMUNITY
        return AssuranceTier.VALIDATED

    @property
    def may_claim_physical_behaviour(self) -> bool:
        return self.tier_ceiling.may_claim_physical_behaviour


class OperatingMode(StrEnum):
    """The collaborative operation in force at a sample, per ISO 10218-2 / ISO/TS 15066.

    The mode decides which checks apply. Speed and separation monitoring is
    meaningless while the machine is stopped, and a power-and-force limit is
    meaningless while nothing is in contact.
    """

    #: Full speed, safeguarded space assumed clear by a fixed guard or interlock.
    AUTOMATIC = "automatic"
    #: Reduced-speed control, typically for teaching or setup.
    REDUCED_SPEED = "reduced_speed"
    #: Operator commands motion directly through a hand-guiding device.
    HAND_GUIDING = "hand_guiding"
    #: Speed and separation monitoring: the cell keeps a computed distance.
    SSM = "ssm"
    #: Power and force limiting: contact is permitted within energy limits.
    PFL = "pfl"
    #: Safety-rated stop, or standstill.
    STOPPED = "stopped"

    @property
    def separation_is_the_control(self) -> bool:
        """Whether a computed distance is what makes this mode safe.

        Only speed and separation monitoring. In automatic mode the protective
        measure is the fixed guard or interlock, not a distance, so applying the
        separation formula there would report a violation on every sample of a
        perfectly safe fenced cell. A person detected during automatic operation
        is a finding, but it is the ``mode_consistency`` finding, not a
        separation shortfall.
        """
        return self is OperatingMode.SSM

    @property
    def contact_is_permitted(self) -> bool:
        return self in (OperatingMode.PFL, OperatingMode.HAND_GUIDING)


@dataclass(frozen=True)
class Sample:
    """One instant of machine state.

    Distances are millimetres, speeds millimetres per second, forces newtons,
    areas square centimetres, time seconds from the trace epoch. Units are not
    negotiable and are not carried per field: a trace that arrives in metres is
    a conversion the caller performs before it reaches this class, because a
    silent unit error in a separation distance is a person in hospital.
    """

    t: float
    tcp: tuple[float, float, float]
    tcp_speed: float
    mode: OperatingMode
    #: Minimum measured distance to the nearest detected person, mm.
    #: ``None`` means the sensing system detected nobody — which is a claim in
    #: itself, and is only as good as the sensing system's coverage.
    separation: float | None = None
    #: Closing speed of the detected person, mm/s, when the sensing system
    #: reports it. ``None`` falls back to the envelope's declared figure.
    human_speed: float | None = None
    #: Measured contact force, N. Only meaningful in a contact-permitting mode.
    contact_force: float | None = None
    #: Contact area, cm². Needed to turn a force into a pressure.
    contact_area: float | None = None
    #: Which body region the contact is credited to, keyed to the limits table.
    body_region: str = ""

    def __post_init__(self) -> None:
        if self.tcp_speed < 0:
            raise TraceError(f"t={self.t}: tcp_speed is negative ({self.tcp_speed}).")
        if self.separation is not None and self.separation < 0:
            raise TraceError(f"t={self.t}: separation is negative ({self.separation}).")
        if len(self.tcp) != 3:
            raise TraceError(f"t={self.t}: tcp needs three coordinates, got {len(self.tcp)}.")

    def to_dict(self) -> dict[str, Any]:
        return {
            "t": self.t,
            "tcp": list(self.tcp),
            "tcp_speed": self.tcp_speed,
            "mode": self.mode.value,
            "separation": self.separation,
            "human_speed": self.human_speed,
            "contact_force": self.contact_force,
            "contact_area": self.contact_area,
            "body_region": self.body_region,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Sample:
        def opt(key: str) -> float | None:
            v = d.get(key)
            if v is None or v == "":
                return None
            return float(v)

        tcp = d.get("tcp")
        if tcp is None:
            tcp = [d.get("x", 0.0), d.get("y", 0.0), d.get("z", 0.0)]
        return cls(
            t=float(d["t"]),
            tcp=(float(tcp[0]), float(tcp[1]), float(tcp[2])),
            tcp_speed=float(d["tcp_speed"]),
            mode=OperatingMode(str(d["mode"])),
            separation=opt("separation"),
            human_speed=opt("human_speed"),
            contact_force=opt("contact_force"),
            contact_area=opt("contact_area"),
            body_region=str(d.get("body_region", "") or ""),
        )


@dataclass(frozen=True)
class Trace:
    """A run, with the facts needed to decide what it may be used to claim."""

    trace_id: str
    provenance: Provenance
    #: The producing system: controller make and firmware, simulator and version.
    source_system: str
    #: UTC instant of ``t = 0``.
    started_at: datetime
    sample_rate_hz: float
    samples: tuple[Sample, ...]
    #: Free-form conditions: payload, tool, temperature, operator, work order.
    conditions: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.samples:
            raise TraceError(f"trace {self.trace_id!r} has no samples.")
        if self.started_at.tzinfo is None:
            raise TraceError(f"trace {self.trace_id!r} started_at has no timezone.")
        if self.sample_rate_hz <= 0:
            raise TraceError(f"trace {self.trace_id!r} sample_rate_hz must be positive.")
        times = [s.t for s in self.samples]
        if any(b <= a for a, b in zip(times, times[1:], strict=False)):
            raise TraceError(
                f"trace {self.trace_id!r} samples are not strictly increasing in t. "
                "An out-of-order trace cannot support a claim about a stop time."
            )

    @property
    def duration_s(self) -> float:
        return self.samples[-1].t - self.samples[0].t

    @property
    def gaps(self) -> list[tuple[float, float]]:
        """Intervals longer than twice the nominal sample period.

        A gap is where the evidence is silent. A protective stop that happened
        inside a gap was not recorded, whatever the surrounding samples imply.
        """
        nominal = 1.0 / self.sample_rate_hz
        out: list[tuple[float, float]] = []
        for a, b in zip(self.samples, self.samples[1:], strict=False):
            if (b.t - a.t) > 2 * nominal:
                out.append((a.t, b.t))
        return out

    def modes_present(self) -> list[OperatingMode]:
        seen: list[OperatingMode] = []
        for s in self.samples:
            if s.mode not in seen:
                seen.append(s.mode)
        return seen

    def hashable_payload(self) -> dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "provenance": self.provenance.value,
            "source_system": self.source_system,
            "started_at": format_utc(self.started_at),
            "sample_rate_hz": self.sample_rate_hz,
            "conditions": self.conditions,
            "samples": [s.to_dict() for s in self.samples],
        }

    def content_hash(self) -> str:
        """Identity of the run. Two traces with the same hash are the same run."""
        return content_hash_of(self.hashable_payload())

    def __len__(self) -> int:
        return len(self.samples)

    def __iter__(self) -> Iterator[Sample]:
        return iter(self.samples)

    # -- loading ----------------------------------------------------------
    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Trace:
        return cls(
            trace_id=str(d["trace_id"]),
            provenance=Provenance(str(d["provenance"])),
            source_system=str(d["source_system"]),
            started_at=parse_utc(str(d["started_at"])),
            sample_rate_hz=float(d["sample_rate_hz"]),
            samples=tuple(Sample.from_dict(s) for s in d["samples"]),
            conditions=dict(d.get("conditions") or {}),
        )

    @classmethod
    def from_json(cls, path: str | Path) -> Trace:
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))

    @classmethod
    def from_csv(
        cls,
        path: str | Path,
        *,
        trace_id: str,
        provenance: Provenance,
        source_system: str,
        started_at: datetime,
        sample_rate_hz: float,
        conditions: dict[str, Any] | None = None,
    ) -> Trace:
        """Read samples from a controller log.

        The metadata a controller does not record — what produced the file, when
        it started, whether it is a simulation — must be supplied by the caller.
        There is no default for ``provenance`` on purpose: the one field that
        decides what the run may prove is the one field nobody may omit.
        """
        rows = list(csv.DictReader(Path(path).open(newline="", encoding="utf-8")))
        if not rows:
            raise TraceError(f"{path} has no rows.")
        return cls(
            trace_id=trace_id,
            provenance=provenance,
            source_system=source_system,
            started_at=started_at,
            sample_rate_hz=sample_rate_hz,
            samples=tuple(Sample.from_dict(r) for r in rows),
            conditions=dict(conditions or {}),
        )

    @classmethod
    def of(cls, samples: Iterable[Sample], **kw: Any) -> Trace:
        seq: Sequence[Sample] = tuple(samples)
        return cls(samples=tuple(seq), **kw)
